#175494059 Login with Email and Password
Soma-Technologies-Inc/visitAfrica-backend pull request #16
Opened 2020-11-25 19:52 UTC by LouangeMu

-login with email
- login with password

[Starts #175494059]

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### Screenshots (if appropriate)
#### Questions:

2020-12-06 01:35 UTC, tigthor commented
- work on the pr Description of how this should be tested add adequate information
- You should not that the reason why your tests are failing is that you are requiring login data that are not in the database so before you require data in the database you need to have them there . You can use different methods of entering userdata in the database like using signup route on your test and create a new user or seeding the user in the database.

2020-12-06 01:40 UTC, tigthor commented on preview.html
> -
This file is not needed

2020-12-06 01:41 UTC, tigthor requested changes
After working on other comments I left on your pr remember also to squash your commits into 1

2020-12-07 11:57 UTC, tigthor approved these changes
LGTM

2020-12-09 13:07 UTC, Niyonsengaeric commented
LGTM!

2020-12-09 13:08 UTC, Niyonsengaeric approved these changes

2020-12-09 13:08 UTC, merged