#175494074 ft:Users should be able to make multi city request
Soma-Technologies-Inc/visitAfrica-backend pull request #36
Opened 2020-12-15 00:06 UTC by tigthor

[start 175494074]

#### What does this PR do?
- work in progres
- create multi city trip
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### Screenshots (if appropriate)
#### Questions:

2020-12-16 05:15 UTC, Niyonsengaeric commented
@tigthor, please make a correction on What does this PR do? session.

- is this the right status code?

![403 setting authorization](https://user-images.githubusercontent.com/50768983/102307505-4239c700-3f6d-11eb-926b-096c8cd796f9.png)

- change your request body to be a JSON object, not an array.
-  @tigthor  can you make it one request with one departure date and return date with those multi-stop on it.

2020-12-16 07:57 UTC, tigthor commented
> @tigthor, please make a correction on What does this PR do? session.
> 
> * is this the right status code?
> 
> ![403 setting authorization](https://user-images.githubusercontent.com/50768983/102307505-4239c700-3f6d-11eb-926b-096c8cd796f9.png)
> 
> * change your request body to be a JSON object, not an array.
> * @tigthor  can you make it one request with one departure date and return date with those multi-stop on it.

Yes I am gonna work on that

2020-12-16 09:52 UTC, Liliane003 commented
LGTM

2020-12-21 19:54 UTC, Niyonsengaeric requested changes

2020-12-21 19:54 UTC, Niyonsengaeric commented on src/database/migrations/20201129004549-create-user.js
> +		lineManagerId: {
why are you hardcoding lineManager?

2020-12-22 11:35 UTC, merged