Return Trip
Soma-Technologies-Inc/visitAfrica-backend pull request #37
Opened 2020-12-15 07:47 UTC by Liliane003

[start:175494070]
[finish:175494070]

#### What does this PR do?

- user should be able to return trip

#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### Screenshots (if appropriate)
#### Questions:

2020-12-18 12:49 UTC, BenieSereine commented on src/tests/users/get-users.test.js
> +				.set('authorization', `bearer ${expiredToken}`)
Why did you change to lowercase?

2020-12-18 20:33 UTC, tigthor commented on src/controllers/trip.controller.js
> +		console.log(tripRequest);
Remove console log

2020-12-18 20:35 UTC, tigthor commented on src/controllers/trip.controller.js
> +		if (!trip) {
If conditions are put in middlewares not in controller

2020-12-18 20:37 UTC, tigthor commented on src/routes/trip.route.js
> +router.post('/return_trip', validateReturnTrip, protectRoute, TripController.returnTripController);
Before continuing to validate input you should pass from protectRoute to validateReturnTrip

2020-12-18 20:38 UTC, tigthor commented on src/tests/trip/trip.test.js
> +import { userToVerify, userToken, tokenToVerify, returnTrip } from '../fixtures/user.fixture';
Work on these Hound feedbacks

2020-12-18 20:41 UTC, tigthor commented on src/validations/trip.validation.js
> +				.regex(/^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$/)
In this file ask yourself this question. What can happen if a user enter a returning date less than starting date that would be a disaster

2020-12-18 20:42 UTC, tigthor requested changes
Please work on feedbacks I left on your pr

2020-12-18 20:47 UTC, tigthor commented
@Liliane003  Work on your pr description and how can this be tested

2020-12-21 13:28 UTC, BenieSereine approved these changes

2020-12-22 12:27 UTC, Niyonsengaeric requested changes

2020-12-22 12:27 UTC, Niyonsengaeric commented on package.json
> +    "migrate": "npx sequelize db:migrate:undo:all && npx sequelize db:migrate && npx sequelize db:seed:all",
why are you changing this?

2020-12-22 14:13 UTC, merged