#175494040 Configuration of a sequelize
Soma-Technologies-Inc/visitAfrica-backend pull request #8
Opened 2020-11-19 12:28 UTC by LouangeMu

What does this PR do?

This PR shows the setting up of a sequerizer.

Description of PR to be completed
It sets up a Sequerizer

How should this be manually tested
N/A

Any background context you want to provide?
N/A
**What are the relevant pivotal tracker stories?

2020-11-19 15:02 UTC, tigthor commented on src/database/config/config.js
> +<<<<<<< HEAD
remove this conflict

2020-11-19 15:03 UTC, tigthor commented on src/database/config/config.js
> +>>>>>>> dfe129ac0e00169f2ec4039c2720730a4bf20050
These conflicts should be removed

2020-11-19 15:03 UTC, tigthor commented on src/database/models/index.js
> +>>>>>>> dfe129ac0e00169f2ec4039c2720730a4bf20050
still these are conflicts

2020-11-19 15:09 UTC, tigthor commented
And Mentor Vandy is not your teammate.He is our mentor so i don't understand why he should be added in your peer review

2020-11-19 20:05 UTC, tigthor approved these changes

2020-11-20 14:28 UTC, erickyvand requested changes

2020-11-20 14:28 UTC, erickyvand commented on .gitignore
> +.env
add new line

2020-11-20 14:28 UTC, erickyvand commented on src/database/config/config.js
> +require('dotenv').config();
import using `ES6 syntax`

2020-11-20 14:28 UTC, erickyvand commented on src/database/models/index.js
> +  sequelize = new Sequelize(config.database, config.username, config.password, config);
This line of code `config.database, config.username, config.password,` should be replaced with `config.url`

2020-11-21 09:37 UTC, Niyonsengaeric approved these changes

2020-11-21 09:37 UTC, Niyonsengaeric approved these changes

2020-11-21 09:41 UTC, merged