configuring express and change some babel dependency
Soma-Technologies-Inc/visitAfrica-backend pull request #9
Opened 2020-11-19 16:09 UTC by eustacheAki

**What does this PR do?**
this PR is for configuring express

**Description of Task to be completed?**
this PR is for configuring express in VisitAfrica-backend

**How should this be manually tested?**

After the cloned this repository(https://github.com/Soma-Technologies-Inc/visitAfrica-backend.git) run npm install and once set up is done run npm run start-dev then use postman to test this endpoint
_GET request_
visit: http://localhost:3000/

**Any background context you want to provide?**
N/A

**What are the relevant pivotal tracker stories?**
[#175800938]

**Screenshot (if appropriate)**  

Those are the screen shoot for testing get appropriate routes and detect errors if you type bad requests.
![Screenshot (96)](https://user-images.githubusercontent.com/69468875/99691563-0a388480-2a92-11eb-959c-9f3e5770bbbc.png)
![Screenshot (97)](https://user-images.githubusercontent.com/69468875/99691569-0c024800-2a92-11eb-9f64-adb8762c3529.png)

2020-11-19 20:12 UTC, LouangeMu approved these changes
well done.

2020-11-19 20:16 UTC, LouangeMu commented
Please consider to not put your Mentor in Team mate review.

2020-11-19 20:22 UTC, erickyvand requested changes

2020-11-19 20:22 UTC, erickyvand commented on .babelrc
> + }
add new line

2020-11-20 08:03 UTC, erickyvand approved these changes

2020-11-20 09:15 UTC, Niyonsengaeric approved these changes

2020-11-20 09:16 UTC, merged